/* ==========================================================================
   PMO Suite - Oracle Database DDL
   ========================================================================== */

-- 1. Projects Table
CREATE TABLE PROJECTS (
    ID              VARCHAR2(50) NOT NULL,
    NAME            VARCHAR2(200) NOT NULL,
    CODE            VARCHAR2(50) NOT NULL,
    CLIENT          VARCHAR2(100),
    TYPE            VARCHAR2(20) NOT NULL, -- 'External', 'Internal', 'Other'
    ORDER_AMOUNT    NUMBER(18, 2) DEFAULT 0,
    START_DATE      DATE,
    END_DATE        DATE,
    STATUS          VARCHAR2(20) DEFAULT 'Planning', -- 'Planning', 'Active', 'Completed', 'On Hold'
    CREATED_AT      DATE DEFAULT SYSDATE,
    UPDATED_AT      DATE DEFAULT SYSDATE,
    CONSTRAINT PK_PROJECTS PRIMARY KEY (ID),
    CONSTRAINT UQ_PROJECTS_CODE UNIQUE (CODE),
    CONSTRAINT CHK_PROJECTS_TYPE CHECK (TYPE IN ('External', 'Internal', 'Other')),
    CONSTRAINT CHK_PROJECTS_STATUS CHECK (STATUS IN ('Planning', 'Active', 'Completed', 'On Hold'))
);

COMMENT ON TABLE PROJECTS IS 'Project Information';
COMMENT ON COLUMN PROJECTS.TYPE IS 'Project Type: External, Internal, Other';
COMMENT ON COLUMN PROJECTS.ORDER_AMOUNT IS 'Contract amount in KRW';

-- 2. Members Table
CREATE TABLE MEMBERS (
    ID              VARCHAR2(50) NOT NULL,
    NAME            VARCHAR2(100) NOT NULL,
    POSITION        VARCHAR2(50), -- e.g., 'Senior', 'Junior'
    CREATED_AT      DATE DEFAULT SYSDATE,
    CONSTRAINT PK_MEMBERS PRIMARY KEY (ID)
);

COMMENT ON TABLE MEMBERS IS 'Resource Pool Members';

-- 3. Member Skills Table
CREATE TABLE MEMBER_SKILLS (
    MEMBER_ID       VARCHAR2(50) NOT NULL,
    SKILL_NAME      VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_MEMBER_SKILLS PRIMARY KEY (MEMBER_ID, SKILL_NAME),
    CONSTRAINT FK_MS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(ID) ON DELETE CASCADE
);

COMMENT ON TABLE MEMBER_SKILLS IS 'Skills possessed by members';

-- 4. Assignments Table
CREATE TABLE ASSIGNMENTS (
    ID              VARCHAR2(50) NOT NULL,
    PROJECT_ID      VARCHAR2(50) NOT NULL,
    MEMBER_ID       VARCHAR2(50) NOT NULL,
    ROLE            VARCHAR2(20), -- 'PM', 'PL', 'DEV', etc.
    START_DATE      DATE NOT NULL,
    END_DATE        DATE NOT NULL,
    INPUT_RATIO     NUMBER(3, 2) DEFAULT 1.0, -- 0.0 to 1.0
    CREATED_AT      DATE DEFAULT SYSDATE,
    UPDATED_AT      DATE DEFAULT SYSDATE,
    CONSTRAINT PK_ASSIGNMENTS PRIMARY KEY (ID),
    CONSTRAINT FK_ASN_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ASN_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(ID) ON DELETE CASCADE
);

COMMENT ON TABLE ASSIGNMENTS IS 'Resource Allocation to Projects';
COMMENT ON COLUMN ASSIGNMENTS.INPUT_RATIO IS 'Man-Month Ratio (0.0 ~ 1.0)';
